-- Historical migration notes only; do not execute this file.
--
-- The original file mixed raw date headings with ALTER TABLE statements and
-- could not be run as SQL. Its final intended state has been incorporated into
-- app/backend/migrations/versions/20260730_0001_initial_schema.py.
--
-- Use Alembic for normal setup:
--   cd app/backend
--   .\.venv\Scripts\python.exe -m alembic upgrade head
--
-- Use app/sql/bootstrap.sql only when a standalone SQL bootstrap is required.
